//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogue
    {
        public catalogue()
        {
            this.deliverOrderDetails = new HashSet<deliverOrderDetail>();
            this.inventories = new HashSet<inventory>();
            this.inventoryAdjDetails = new HashSet<inventoryAdjDetail>();
            this.purchaseOrderDetails = new HashSet<purchaseOrderDetail>();
            this.quotationDetails = new HashSet<quotationDetail>();
            this.requisitionByDeptDetails = new HashSet<requisitionByDeptDetail>();
            this.requisitionDetails = new HashSet<requisitionDetail>();
            this.stockcards = new HashSet<stockcard>();
            this.stockLevels = new HashSet<stockLevel>();
            this.unfulfills = new HashSet<unfulfill>();
        }
    
        public string item_code { get; set; }
        public int catg_id { get; set; }
        public string description { get; set; }
        public Nullable<int> reorder_level { get; set; }
        public Nullable<int> reorder_quantity { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> item_price { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<deliverOrderDetail> deliverOrderDetails { get; set; }
        public virtual ICollection<inventory> inventories { get; set; }
        public virtual ICollection<inventoryAdjDetail> inventoryAdjDetails { get; set; }
        public virtual ICollection<purchaseOrderDetail> purchaseOrderDetails { get; set; }
        public virtual ICollection<quotationDetail> quotationDetails { get; set; }
        public virtual ICollection<requisitionByDeptDetail> requisitionByDeptDetails { get; set; }
        public virtual ICollection<requisitionDetail> requisitionDetails { get; set; }
        public virtual ICollection<stockcard> stockcards { get; set; }
        public virtual ICollection<stockLevel> stockLevels { get; set; }
        public virtual ICollection<unfulfill> unfulfills { get; set; }
    }
}
