//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class deliverOrder
    {
        public deliverOrder()
        {
            this.deliverOrderDetails = new HashSet<deliverOrderDetail>();
        }
    
        public string do_id { get; set; }
        public string po_id { get; set; }
        public string sup_code { get; set; }
        public Nullable<System.DateTime> do_date { get; set; }
        public Nullable<int> dept_id { get; set; }
        public string status { get; set; }
    
        public virtual department department { get; set; }
        public virtual purchaseOrder purchaseOrder { get; set; }
        public virtual supplier supplier { get; set; }
        public virtual ICollection<deliverOrderDetail> deliverOrderDetails { get; set; }
    }
}
