//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class department
    {
        public department()
        {
            this.deliverOrders = new HashSet<deliverOrder>();
            this.employees = new HashSet<employee>();
            this.requisitions = new HashSet<requisition>();
            this.requisitionByDepts = new HashSet<requisitionByDept>();
            this.unfulfills = new HashSet<unfulfill>();
        }
    
        public int dept_id { get; set; }
        public string dept_code { get; set; }
        public string dept_name { get; set; }
        public string dept_phone { get; set; }
        public string dept_fax { get; set; }
        public int col_id { get; set; }
    
        public virtual collectionPoint collectionPoint { get; set; }
        public virtual ICollection<deliverOrder> deliverOrders { get; set; }
        public virtual ICollection<employee> employees { get; set; }
        public virtual ICollection<requisition> requisitions { get; set; }
        public virtual ICollection<requisitionByDept> requisitionByDepts { get; set; }
        public virtual ICollection<unfulfill> unfulfills { get; set; }
    }
}
