//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventoryAdj
    {
        public inventoryAdj()
        {
            this.inventoryAdjDetails = new HashSet<inventoryAdjDetail>();
        }
    
        public string voucher_id { get; set; }
        public Nullable<System.DateTime> date_issue { get; set; }
        public Nullable<int> emp_supervisor_id { get; set; }
        public Nullable<int> emp_auth_id { get; set; }
        public string status { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual ICollection<inventoryAdjDetail> inventoryAdjDetails { get; set; }
    }
}
