//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventoryAdjDetail
    {
        public string voucher_id { get; set; }
        public string item_code { get; set; }
        public Nullable<int> quantity { get; set; }
        public string reason { get; set; }
    
        public virtual catalogue catalogue { get; set; }
        public virtual inventoryAdj inventoryAdj { get; set; }
    }
}
