//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchaseOrderDetail
    {
        public purchaseOrderDetail()
        {
            this.unfulfills = new HashSet<unfulfill>();
        }
    
        public string po_id { get; set; }
        public string item_code { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual catalogue catalogue { get; set; }
        public virtual purchaseOrder purchaseOrder { get; set; }
        public virtual ICollection<unfulfill> unfulfills { get; set; }
    }
}
