//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class quotation
    {
        public quotation()
        {
            this.quotationDetails = new HashSet<quotationDetail>();
        }
    
        public int quo_id { get; set; }
        public string sup_code { get; set; }
        public int year { get; set; }
    
        public virtual supplier supplier { get; set; }
        public virtual ICollection<quotationDetail> quotationDetails { get; set; }
    }
}
