//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisition
    {
        public requisition()
        {
            this.requisitionDetails = new HashSet<requisitionDetail>();
        }
    
        public int req_id { get; set; }
        public Nullable<int> dept_id { get; set; }
        public Nullable<int> req_emp_id { get; set; }
        public Nullable<System.DateTime> req_date { get; set; }
        public Nullable<System.DateTime> approve_date { get; set; }
        public Nullable<int> approve_emp_id { get; set; }
        public Nullable<int> received_emp_id { get; set; }
        public Nullable<System.DateTime> received_date { get; set; }
        public string req_status { get; set; }
        public string req_reason { get; set; }
    
        public virtual department department { get; set; }
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual employee employee2 { get; set; }
        public virtual ICollection<requisitionDetail> requisitionDetails { get; set; }
    }
}
