//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisitionByDept
    {
        public requisitionByDept()
        {
            this.requisitionByDeptDetails = new HashSet<requisitionByDeptDetail>();
        }
    
        public int req_dept_id { get; set; }
        public Nullable<int> dept_id { get; set; }
        public Nullable<System.DateTime> req_date { get; set; }
        public string status { get; set; }
    
        public virtual department department { get; set; }
        public virtual ICollection<requisitionByDeptDetail> requisitionByDeptDetails { get; set; }
    }
}
