//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.employees = new HashSet<employee>();
        }
    
        public int role_id { get; set; }
        public string role1 { get; set; }
    
        public virtual ICollection<employee> employees { get; set; }
    }
}
