//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class stationery_trend_report_view
    {
        public int req_dept_id { get; set; }
        public Nullable<int> dept_id { get; set; }
        public Nullable<System.DateTime> req_date { get; set; }
        public string status { get; set; }
        public string item_code { get; set; }
        public Nullable<int> req_quantity { get; set; }
        public string description { get; set; }
        public string name { get; set; }
        public int catg_id { get; set; }
        public string dept_name { get; set; }
        public Nullable<int> OrderMonth { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
