//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class stationery_inventory_view
    {
        public string item_code { get; set; }
        public Nullable<int> reorder_level { get; set; }
        public string unit { get; set; }
        public string name { get; set; }
        public Nullable<int> reorder_quantity { get; set; }
        public Nullable<int> balance { get; set; }
        public string description { get; set; }
    }
}
