//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public supplier()
        {
            this.deliverOrders = new HashSet<deliverOrder>();
            this.purchaseOrders = new HashSet<purchaseOrder>();
            this.quotations = new HashSet<quotation>();
        }
    
        public string sup_code { get; set; }
        public string sup_name { get; set; }
        public string contact_name { get; set; }
        public string sup_phone { get; set; }
        public string sup_fax { get; set; }
        public string sup_address { get; set; }
        public string sup_gst { get; set; }
        public string sup_status { get; set; }
        public string sup_rank { get; set; }
    
        public virtual ICollection<deliverOrder> deliverOrders { get; set; }
        public virtual ICollection<purchaseOrder> purchaseOrders { get; set; }
        public virtual ICollection<quotation> quotations { get; set; }
    }
}
