//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class unfulfill
    {
        public int id { get; set; }
        public string item_code { get; set; }
        public Nullable<int> dept_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> unfufil_date { get; set; }
        public string remark { get; set; }
        public string @ref { get; set; }
        public string status { get; set; }
    
        public virtual catalogue catalogue { get; set; }
        public virtual department department { get; set; }
        public virtual purchaseOrderDetail purchaseOrderDetail { get; set; }
    }
}
