//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_poReport
    {
        public string po_id { get; set; }
        public string item_code { get; set; }
        public int catg_id { get; set; }
        public string description { get; set; }
        public string name { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> po_date { get; set; }
        public string status { get; set; }
        public Nullable<decimal> total { get; set; }
    }
}
