//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_cataloguePrice
    {
        public string item_code { get; set; }
        public int catg_id { get; set; }
        public string description { get; set; }
        public Nullable<int> reorder_level { get; set; }
        public Nullable<int> reorder_quantity { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> price { get; set; }
        public string itemCode { get; set; }
    }
}
